# Generated by Django 2.1.7 on 2019-09-09 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190622_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'Learnings',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('addedBy', models.ForeignKey(db_column='added_by', on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LessonGroups',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='lessonGroup',
            field=models.ForeignKey(db_column='lesson_group_id', on_delete=django.db.models.deletion.CASCADE, to='lessons.LessonGroup'),
        ),
        migrations.AddField(
            model_name='learning',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
        ),
        migrations.AddField(
            model_name='learning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
